댓글_대댓글/myproject/comment_app/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True) 

    class Meta:
        ordering = ['-date']
        
    def __str__(self):
        return self.body
         
class Comment(models.Model):
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.comment
    
class CommentReply(models.Model):
    comment_reply = models.ForeignKey(Comment, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

댓글_대댓글/myproject/comment_app/forms.py
from django import forms
from .models import Post, Comment, CommentReply

class PostForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.Textarea(attrs={
        'class': 'post-new-content',
        'rows': 5,
        'cols': 50,
        'placeholder': '140자 까지 등록 가능합니다.', }))

    class Meta:
        model = Post
        fields = ['title', 'body']
        
        
        
class CommentForm(forms.ModelForm):
    comment = forms.CharField(label='', widget=forms.Textarea(attrs={
        'rows': 5,
        'cols': 50,
        'placeholder': '댓글을 적어 주세요.', }))

    class Meta:
        model = Comment
        fields = ['comment']
        
class CommentReplyForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'rows': 5,
        'cols': 50,
        'placeholder': '대댓글을 입력해주세요.', }))

    class Meta:
        model = CommentReply
        fields = ['content']

댓글_대댓글/myproject/comment_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment, CommentReply
from .forms import PostForm, CommentForm, CommentReplyForm

# 메인 홈
def home(request):
    # posts = Post.objects.all() 
    posts = Post.objects.filter().order_by('-date')
    return render(request, 'home.html', {'posts': posts})


# 새 글 생성
def post_new(request):
    if request.method == 'POST' or request.method == "FILES":
        form = PostForm(request.POST, request.FILES)       
        if form.is_valid():
            unfinished = form.save(commit=False)
            unfinished.save()
            return redirect('home')
    else:
        form = PostForm()
    return render(request, 'post_new.html', {'form':form})

# 게시글 상세페이지
def post_detail(request, post_id):
    detail = get_object_or_404(Post, pk=post_id) 
    comment_form = CommentForm()
    comment_reply_form = CommentReplyForm()
    return render(request, 'post_detail.html', {'detail':detail, 'comment_form':comment_form, 'comment_reply_form':comment_reply_form})


# 댓글 
def comment_new(request, post_id):
    filled_form = CommentForm(request.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False)
        finished_form.post = get_object_or_404(Post, pk=post_id)
        finished_form.save()
    return redirect('post_detail', post_id)


# 대댓글
def commentreply(request, comment_id):
    form = CommentReplyForm(request.POST)
    if form.is_valid():
        finished = form.save(commit=False)
        finished.comment_reply = get_object_or_404(Comment, pk=comment_id)
        finished.save()
    return redirect('post_detail', post_id=finished.comment_reply.post.id)

댓글_대댓글/myproject/comment_app/templates/home.html
<h1>메인 홈화면입니다.</h1>

<a href="{% url 'post_new' %}">새 글 작성</a>
<br>
<hr>
<tbody>
{% for post in posts %}
<tr>
    <h4>글 목록</h4>
	<td><a href = "{% url 'post_detail' post.id %}">제목 : {{ post.title }}</a></td><br>
    <hr>
</tr>
<br><br>
{% endfor %}
</tbody>

댓글_대댓글/myproject/comment_app/templates/post_detail.html
<h1>생성한 글 확인</h1>

<h2> 제목 : {{ detail.title }}</h2>

<h2> 본문 </h2>
{{ detail.body }}



<hr>

<h3>댓글</h3>
<br>

{% for comment in detail.comment_set.all %}
    <P>{{ comment }} | {{ comment.comment_name }} | {{ comment.created_at|date:'Y.m.d' }}</P>
    {% for content in comment.commentreply_set.all %}
        <P>&nbsp&nbsp ↳  {{ content }} | {{ content.comment_reply_name }} | {{ content.created_at|date:'Y.m.d' }}</P>
    {% endfor %}
    {% if detail.comment_set.count > 0 %}
        <form method="POST" action="{% url 'commentreply' comment.id %}">
            {% csrf_token %}
            {{ comment_reply_form }}
            <input type = "submit" value="대댓글 입력">
        </form>
    {% endif %}
{% empty %}
    <p>댓글이 없습니다.</p>
{% endfor %}

<hr>
<form method="POST" action="{% url 'comment_new' detail.id %}">
    {% csrf_token %}
    {{ comment_form }}
    <input type = "submit" value="댓글 입력">
</form>

댓글_대댓글/myproject/comment_app/templates/post_new.html
<h1> 새 글 작성 </h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type='submit' value="새 글 생성하기">
</form>